### ISSUE TITLE
No issue, but de.lua

### ISSUE THREAD

**Issue by porterslug** [L0stedMrlion/lion_mechanic#1]
{
  "nodamaged": "Das Fahrzeug hat keine Beschädigungen!",
  "vehiclefixed": "Das Fahrzeug wurde repariert!",
  "novehnearby": "Kein Fahrzeug in der Nähe!",
  "notenoughmoney": "Du hast zu wenig Geld dabei! Du brauchst $%s"
}

**Comment by L0stedMrlion** [comment]
Added, thanks!
